### ISSUE TITLE
Vulnerabilities in Firebase Database Rules

### ISSUE THREAD

**Issue by omer88** [neojato/DeLorean-v2#15]
There are security issues with the current Firebase Database Rules.

## Expected Behavior
As I understand from the security rules, data under `/$year/schedules/$user_id` should be read only by a Google authenticated user with uid: `$user_id` and data under `/$year/sessions/$session_id/surveys"` should be read only by admin.

## Current Behavior
An attacker can arbitrarily read data from `/$year/schedules/$user_id` and `/$year/sessions/$session_id/surveys"`. 

A more elaborated explanation of the vulnerability can be [found here](https://noless.io/report/-L7UT1i8R5vs0b57N59h/ddf82c89-5efe-4fc3-beec-09a656d46348).

## Possible Solution
A possible solution is to remove the rule `".read": "true",` from `/` , but in order not to break any functionality, each path should be specified with its appropriate read rule.

In order to generate another report, after fixing the issue, you can login into https://noless.io.

**Comment by neojato** [comment]
This is due to the cascading nature of [Firebase RTDB Rules](https://firebase.google.com/docs/database/security/securing-data#read_and_write_rules_cascade).

Since the secured areas are nested within a parent that allows anyone to read, it would require some refactoring of the Data Model to extract those out into their own parent nodes.

**Comment by neojato** [comment]
With the rules updated in [015c1e6](https://github.com/neojato/DeLorean-v2/commit/015c1e68226efa380a386f28fbff13dda26c23bf) I'm keen to close this one as I've not been able to reproduce the security issue mentioned.
