### ISSUE TITLE
Configurable custom header code

### ISSUE THREAD

**Issue by cjwhitsitt** [neojato/DeLorean-v2#3]
In order to do some analytics things, it'd be nice to be able to insert custom code in the page headers.

**Comment by neojato** [comment]
The issue with having a custom header to inject code is security issues, but I see a value in it.

The other issue is that this is a single-page app (SPA) and things like pageviews won't be tracked unless it is custom coded.

**Comment by neojato** [comment]
I've switched/upgraded this project to utilize Google Tag Manager instead of hardcoding Google Analytics page/event tracking as part of commit be10726.

This allows site managers to be able to insert custom HTML and/or utilize many of the available Tags all from within the [Google Tag Manager](https://tagmanager.google.com) interface.

See the step [Google Tag Manager Setup](https://github.com/neojato/DeLorean-v2#google-tag-manager-setup-optional) on how to configure.
